WIP: Translations
takeflight/wagtailpolls pull request #6
Opened 2016-10-24 05:04 UTC by SableWalnut

2016-10-24 05:07 UTC, timheap commented
cc @frague59. Neither @SableWalnut nor I have done much with translations, so your input on this would be appreciated.

2016-10-24 05:35 UTC, mx-moth requested changes
You should set a translated `verbose_name` on all model fields that a user (admin or otherwise) might see:

``` python
class Poll(...):
    title = models.CharField(_('title'), max_length=128)
    # and so on ...
```

---

A thing some projects do, which you may want to use in the future: internal strings use 'single quotes', while user-facing strings use "double quotes". This makes looking for strings that need translation easier, as well as helping a developer understand the context of the string.

---

In the templates, `{% blocktrans %}` is used in a few places like `<title>` tags where `{% trans %}` would be better. It is just a bit less verbose, and more standard for short strings.

2016-10-24 05:35 UTC, timheap commented on wagtailpolls/forms.py
> +                self.add_error(None, _('Sorry, you cannot vote twice in %s minutes') % (settings.VOTE_COOLDOWN))
You should use [`ungettext`](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/#pluralization) for translations including plurals, although this is already broken in English when `VOTE_COOLDOWN = 1`

2016-10-24 05:35 UTC, timheap commented on wagtailpolls/views/vote.py
> +        return HttpResponse("<h1>{0}</h1>".format(_('Oops, there is no poll to vote on!')), status=500)
Error messages do not generally get translated. I would suggest this is better off as `raise Http404` as well, although that change is unrelated to translations.

2016-10-24 05:35 UTC, timheap commented on wagtailpolls/templates/wagtailpolls/poll_list.html
> +						{{ poll.date_created|timesince }} {% blocktrans %}ago{% endblocktrans %}</div>{% endif %}
For situations like this, where there is something like `<quantity> <modifier>`, it is best to translate the whole phrase, like:

```html+django
{% blocktrans with when=poll.date_created|timesince %}{{ when }} ago{% endblocktrans %}
```

Not all languages follow the same structure as English in where they put modifiers for some types of measurements.

2016-10-24 05:35 UTC, timheap commented on wagtailpolls/templates/wagtailpolls/poll_list.html
>  						<div class="human-readable-date" title="{{ poll.date_created|date:"d M Y H:i" }}">
There are a few formats that the `|date` filter understands that produce locale appropriate dates. Under the big table of format options, [the date docs](https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#date) have more info. In this case, something like `{{ poll.date_created|date:"SHORT_DATETIME_FORMAT" }}` would be appropriate.

2016-10-24 05:35 UTC, timheap commented on wagtailpolls/templates/wagtailpolls/poll_list.html
>  						<a href="{% url 'wagtailpolls_results' poll_pk=poll.pk %}" class="icon icon-arrow-right" title="Check out the poll results for '{{poll}}'"><b>Results</b></a>
You missed some strings here

2016-10-24 05:35 UTC, timheap commented on wagtailpolls/templates/wagtailpolls/poll_list.html
> +	<p>{% blocktrans %}Page{% endblocktrans %} {{page.number}} {% blocktrans %}of{% endblocktrans %} {{paginator.num_pages}}</p>
Same comment as above regarding ordering of sentences like this. Something like:

```html+django
<p>{% blocktrans with number=page.number total=paginator.num_pages %}Page {{ number }} of {{ total }}{% endblock %}</p>
```

2016-10-25 12:53 UTC, frague59 commented
I'm working on in on my own fork...

2016-11-06 23:55 UTC, SableWalnut commented
@timheap Made the changes as mentioned in the review! :)

2016-11-07 00:19 UTC, mx-moth requested changes

2016-11-07 00:19 UTC, timheap commented on wagtailpolls/forms.py
> +                self.add_error(None, __('Sorry, you cannot vote twice in %(cooldown)s minutes') % {'cooldown': cooldown})
This is incorrect. `ungettext` takes three arguments: the singular form, the plural form, and the count. Try:
```python
__('Sorry, you can not vote twice in a minute',
   'Sorry, you can not vote twice in %(cooldown)s minutes',
   cooldown) % {'cooldown': cooldown})
```

2016-11-07 00:19 UTC, timheap commented on wagtailpolls/views/vote.py
> +        return Http404("<h1>{0}</h1>".format('Oops, there is no poll to vote on!'))
`raise Http404(...)`  or `return HttpResponseNotFound(...)`, but not `return Http404(...)`. [See the Django docs for more information](https://docs.djangoproject.com/en/1.10/topics/http/views/#the-http404-exception)

2016-11-07 00:29 UTC, SableWalnut commented
Fixed @timheap!

2016-11-07 00:40 UTC, mx-moth approved these changes

2016-11-07 00:40 UTC, timheap commented
Looks good to me now

2016-11-07 00:50 UTC, merged